PySCIPOpt: NLRow Class Reference
NLRow Class Reference
Public Member Functions
def getConstant (self)
def getLinearTerms (self)
def getQuadraticTerms (self)
def hasExprtree (self)
def getLhs (self)
def getRhs (self)
def getDualsol (self)
Static Public Attributes
nlrow = NLRow()
scip_nlrow
Detailed Description
Base class holding a pointer to corresponding SCIP_NLROW
Definition at line 410 of file scip.pyx.
Member Function Documentation
def getConstant (self)
returns the constant of a nonlinear row
Definition at line 427 of file scip.pyx.
References NLRow.scip_nlrow, and SCIPnlrowGetConstant().
def getLinearTerms (self)
returns a list of tuples (var, coef) representing the linear part of a nonlinear row
Definition at line 431 of file scip.pyx.
References NLRow.scip_nlrow, SCIPnlrowGetLinearCoefs(), SCIPnlrowGetLinearVars(), and SCIPnlrowGetNLinearVars().
def getQuadraticTerms (self)
returns a list of tuples (var1, var2, coef) representing the quadratic part of a nonlinear row
Definition at line 438 of file scip.pyx.
References NLRow.scip_nlrow, and SCIPnlrowGetQuadData().
def hasExprtree (self)
returns whether there exists an expression tree in a nonlinear row
Definition at line 455 of file scip.pyx.
References NLRow.scip_nlrow, and SCIPnlrowGetExprtree().
def getLhs (self)
returns the left hand side of a nonlinear row
Definition at line 462 of file scip.pyx.
References NLRow.scip_nlrow, and SCIPnlrowGetLhs().
def getRhs (self)
returns the right hand side of a nonlinear row
Definition at line 466 of file scip.pyx.
References NLRow.scip_nlrow, and SCIPnlrowGetRhs().
def getDualsol (self)
gets the dual NLP solution of a nonlinear row
Definition at line 470 of file scip.pyx.
References NLRow.scip_nlrow, and SCIPnlrowGetDualsol().
The documentation for this class was generated from the following file:
src/pyscipopt/scip.pyx